// Bundled fallback catalog, served when the Perenual API's free-tier daily quota
// is exhausted and nothing usable is cached. Images are hotlinked from Wikimedia
// Commons (stable, public URLs) so no API requests are needed.
//
// Ids start at 900001 to stay far away from real Perenual species ids.
const wiki = (file) => `https://commons.wikimedia.org/wiki/Special:FilePath/${file}?width=700`;

export const SAMPLE_FLOWERS = [
  {
    id: 900001,
    name: "Sweet Briar Rose",
    scientificName: "Rosa rubiginosa",
    family: "Rosaceae",
    cycle: "Perennial",
    image: wiki("Rosa_rubiginosa_1.jpg"),
    price: 42,
    description:
      "A wild European rose with apple-scented foliage and simple five-petaled pink blooms, beloved in cottage hedgerows since medieval times.",
    watering: "Average",
    sunlight: ["Full sun"],
    origin: ["Europe", "Western Asia"],
    attracts: ["Bees", "Birds"],
  },
  {
    id: 900002,
    name: "Garden Tulip",
    scientificName: "Tulipa gesneriana",
    family: "Liliaceae",
    cycle: "Perennial bulb",
    image: wiki("Tulip_-_floriade_canberra.jpg"),
    price: 24,
    description:
      "The classic cupped tulip of Dutch fame — a spring bulb whose single upright bloom comes in nearly every color except true blue.",
    watering: "Average",
    sunlight: ["Full sun", "Part shade"],
    origin: ["Central Asia", "Turkey"],
    attracts: ["Bees"],
  },
  {
    id: 900003,
    name: "Common Sunflower",
    scientificName: "Helianthus annuus",
    family: "Asteraceae",
    cycle: "Annual",
    image: wiki("Sunflower_sky_backdrop.jpg"),
    price: 19,
    description:
      "A towering annual whose golden flower heads track the sun through the day and ripen into seed platters adored by songbirds.",
    watering: "Average",
    sunlight: ["Full sun"],
    origin: ["North America"],
    attracts: ["Bees", "Butterflies", "Birds"],
  },
  {
    id: 900004,
    name: "Oxeye Daisy",
    scientificName: "Leucanthemum vulgare",
    family: "Asteraceae",
    cycle: "Perennial",
    image: wiki("Leucanthemum_vulgare_'Filigran'_Flower_2200px.jpg"),
    price: 21,
    description:
      "A cheerful meadow daisy with crisp white rays around a golden disc — the flower of childhood 'loves me, loves me not' games.",
    watering: "Minimal",
    sunlight: ["Full sun", "Part shade"],
    origin: ["Europe"],
    attracts: ["Bees", "Butterflies"],
  },
  {
    id: 900005,
    name: "Bearded Iris",
    scientificName: "Iris germanica",
    family: "Iridaceae",
    cycle: "Perennial",
    image: wiki("Iris_germanica_(Purple_bearded_Iris),_Wakehurst_Place,_UK_-_Diliff.jpg"),
    price: 36,
    description:
      "Regal purple falls and standards with a fuzzy golden beard — an heirloom rhizome iris that has anchored formal borders for centuries.",
    watering: "Minimal",
    sunlight: ["Full sun"],
    origin: ["Mediterranean"],
    attracts: ["Bees", "Hummingbirds"],
  },
  {
    id: 900006,
    name: "Moth Orchid",
    scientificName: "Phalaenopsis amabilis",
    family: "Orchidaceae",
    cycle: "Perennial",
    image: wiki("Phalaenopsis_(aka).jpg"),
    price: 58,
    description:
      "Arching sprays of moth-shaped blooms that last for months — the most forgiving orchid for a bright windowsill.",
    watering: "Average",
    sunlight: ["Part shade"],
    origin: ["Southeast Asia"],
    attracts: [],
  },
  {
    id: 900007,
    name: "Madonna Lily",
    scientificName: "Lilium candidum",
    family: "Liliaceae",
    cycle: "Perennial bulb",
    image: wiki("Lilium_candidum_1.jpg"),
    price: 44,
    description:
      "Pure white trumpets with a honeyed fragrance, cultivated since antiquity and long a symbol of purity in art and gardens alike.",
    watering: "Average",
    sunlight: ["Full sun", "Part shade"],
    origin: ["Balkans", "Middle East"],
    attracts: ["Butterflies"],
  },
  {
    id: 900008,
    name: "English Lavender",
    scientificName: "Lavandula angustifolia",
    family: "Lamiaceae",
    cycle: "Perennial",
    image: wiki("Single_lavendar_flower02.jpg"),
    price: 26,
    description:
      "Silvery aromatic spikes of violet-blue that perfume the whole garden — clip the stems for sachets that hold their scent for years.",
    watering: "Minimal",
    sunlight: ["Full sun"],
    origin: ["Mediterranean"],
    attracts: ["Bees", "Butterflies"],
  },
  {
    id: 900009,
    name: "Garden Dahlia",
    scientificName: "Dahlia × hybrida",
    family: "Asteraceae",
    cycle: "Perennial tuber",
    image: wiki("Dahlia_x_hybrida.jpg"),
    price: 38,
    description:
      "Late-summer showstoppers in every form from pompon to dinner-plate, blooming tirelessly from midsummer until first frost.",
    watering: "Average",
    sunlight: ["Full sun"],
    origin: ["Mexico", "Central America"],
    attracts: ["Bees", "Butterflies"],
  },
  {
    id: 900010,
    name: "Tropical Hibiscus",
    scientificName: "Hibiscus rosa-sinensis",
    family: "Malvaceae",
    cycle: "Perennial",
    image: wiki("Hibiscus_Brilliant.jpg"),
    price: 34,
    description:
      "Flamboyant scarlet trumpets with a bold central column — each bloom lasts a single day but the plant produces them in endless succession.",
    watering: "Frequent",
    sunlight: ["Full sun"],
    origin: ["East Asia"],
    attracts: ["Hummingbirds", "Butterflies"],
  },
  {
    id: 900011,
    name: "Common Peony",
    scientificName: "Paeonia officinalis",
    family: "Paeoniaceae",
    cycle: "Perennial",
    image: wiki("Paeonia_19.jpg"),
    price: 48,
    description:
      "Lush, ruffled globes of silk-like petals on a plant that can outlive its gardener — peonies routinely bloom for a hundred years.",
    watering: "Average",
    sunlight: ["Full sun", "Part shade"],
    origin: ["Southern Europe"],
    attracts: ["Bees", "Ants"],
  },
  {
    id: 900012,
    name: "Common Poppy",
    scientificName: "Papaver rhoeas",
    family: "Papaveraceae",
    cycle: "Annual",
    image: wiki("Papaver_rhoeas_LC0050.jpg"),
    price: 17,
    description:
      "Tissue-paper petals of brilliant crimson that dance on wiry stems — the wildflower of European cornfields and remembrance.",
    watering: "Minimal",
    sunlight: ["Full sun"],
    origin: ["Europe", "North Africa"],
    attracts: ["Bees"],
  },
  {
    id: 900013,
    name: "Bigleaf Hydrangea",
    scientificName: "Hydrangea macrophylla",
    family: "Hydrangeaceae",
    cycle: "Perennial",
    image: wiki("Hydrangea_macrophylla_-_Hortensia_hydrangea.jpg"),
    price: 40,
    description:
      "Billowing mophead blooms that shift from pink to blue with the soil's chemistry — a living litmus test for the shade garden.",
    watering: "Frequent",
    sunlight: ["Part shade"],
    origin: ["Japan"],
    attracts: ["Butterflies"],
  },
  {
    id: 900014,
    name: "Carnation",
    scientificName: "Dianthus caryophyllus",
    family: "Caryophyllaceae",
    cycle: "Perennial",
    image: wiki("Red_Carnation_NGM_XXXI_p507.jpg"),
    price: 22,
    description:
      "Clove-scented, fringed blooms cultivated for over two thousand years — the florist's workhorse that outlasts nearly every other cut flower.",
    watering: "Average",
    sunlight: ["Full sun"],
    origin: ["Mediterranean"],
    attracts: ["Bees", "Butterflies"],
  },
];

const byId = new Map(SAMPLE_FLOWERS.map((f) => [f.id, f]));

export function getSampleFlowerById(id) {
  return byId.get(Number(id)) || null;
}
